### ISSUE TITLE
Linker error on zug::meta::bottom conversion operators

### ISSUE THREAD

**Issue by ltjax** [arximboldi/zug#9]
I get
```
CMakeFiles/test-into_vector.dir/into_vector.cpp.o: In function `_ZN3zug4skipIRZNKS_5map_tIZL29____C_A_T_C_H____T_E_S_T____4vEUliE0_EclIRKNS_6last_tEEEDaOT_EUlS9_DpOT0_E_NS_4meta6bottomEJiEEENS_11skip_resultIS8_T0_JDpT1_EE4typeES9_OSI_DpOSJ_':
/home/ltjax/code/zug/zug/skip.hpp:186: undefined reference to `zug::meta::bottom::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >() const'
```

and

```
CMakeFiles/test-transducer-eager.dir/transducer/eager.cpp.o: In function `decltype(auto) zug::reduce_nested<zug::last_t const&, zug::meta::bottom, zug::detail::iterator_range<std::reverse_iterator<__gnu_cxx::__normal_iterator<testing::copy_spy<testing::detail::default_copy_spy_base_t>*, std::vector<testing::copy_spy<testing::detail::default_copy_spy_base_t>, std::allocator<testing::copy_spy<testing::detail::default_copy_spy_base_t> > > > >, std::reverse_iterator<__gnu_cxx::__normal_iterator<testing::copy_spy<testing::detail::default_copy_spy_base_t>*, std::vector<testing::copy_spy<testing::detail::default_copy_spy_base_t>, std::allocator<testing::copy_spy<testing::detail::default_copy_spy_base_t> > > > > > >(zug::last_t const&, zug::meta::bottom&&, zug::detail::iterator_range<std::reverse_iterator<__gnu_cxx::__normal_iterator<testing::copy_spy<testing::detail::default_copy_spy_base_t>*, std::vector<testing::copy_spy<testing::detail::default_copy_spy_base_t>, std::allocator<testing::copy_spy<testing::detail::default_copy_spy_base_t> > > > >, std::reverse_iterator<__gnu_cxx::__normal_iterator<testing::copy_spy<testing::detail::default_copy_spy_base_t>*, std::vector<testing::copy_spy<testing::detail::default_copy_spy_base_t>, std::allocator<testing::copy_spy<testing::detail::default_copy_spy_base_t> > > > > >&&)':
/home/ltjax/code/zug/zug/reduce_nested.hpp:47: undefined reference to `zug::meta::bottom::operator testing::copy_spy<testing::detail::default_copy_spy_base_t>&<testing::copy_spy<testing::detail::default_copy_spy_base_t> >() const'
```

With g++ version 7.4.0. I guess this is because bottom's usage in the any_state ctor is not actually an unevaluated context.

**Comment by arximboldi** [comment]
Yeah that is a funny one.  I suspect it is the compiler being dumb. From the errors I do not see how `any_state` is involved, but maybe you think `std::is_base_of` is doing something funny in g++?

**Comment by ltjax** [comment]
Here's a pretty nice explanation: https://stackoverflow.com/questions/35088599/what-are-unevaluated-contexts-in-c

Basically, unevaluated contexts are only expressions in typeid, sizeof, noexcept, and decltype. Does not really matter if is_base_of is implemented in terms of those, because this only applies to expressions, I think

**Comment by ltjax** [comment]
I have traced the problems to the line:
`auto res   = into_vector(xform, v);` in the `"into_vector, transduction"` test
and

`into_vector(reversed, std::move(v));` in the `"eager, moves_data_around"` test

looks like `into_vector` is involved

**Comment by ArtemSarmini** [comment]
````
auto v   = std::vector<std::vector<int>>{{1, 2}, {3}, {4, 5, 6}};
auto res = into_vector(mapcat([](int x) { return x * 2; }), v);
````
Should `res` be vector of ints? Now it is vector of bottoms.

**Comment by arximboldi** [comment]
@ArtemSarmini what compiler and version are you using? That example is extracted from a unit test which is passing...

**Comment by arximboldi** [comment]
(Both clang and gcc from nixpkgs)

**Comment by ArtemSarmini** [comment]
My bad, IDE warning was false positive.

**Comment by arximboldi** [comment]
Thanks for checking!

**Comment by ArtemSarmini** [comment]
Confirmed on gcc 7.5, gcc 10.1 (which amazes me), clang 10.0 is not affected.
This stuff is hard. Gcc emits object code for zug::skip with bottom as state, linker tries to fill relocation (for me -pie is default) symbols for conversion operator call before it understands that this function is never called. IMO it's gcc's fault to it this in the first place. I know no technique to forbid this.

**Comment by ArtemSarmini** [comment]
It seems I found a solution, but I need to either use constexpr if (which requires bumping std version to 17) or write a custom functor (maybe a couple of them). To put it short, we don't need to call zug::skip to query return type, which result_of in into_vector does and which causes the linking problem.
@arximboldi which path is preferred?

**Comment by ArtemSarmini** [comment]
Oh or one can add more overloads and sfinae, 'll try that first.

**Comment by ArtemSarmini** [comment]
Or tag dispatch.

**Comment by arximboldi** [comment]
I would prefer to not bump to C++17 yet. Thanks a lot for investigating this!
